---
deployment:
      tasks:
        - export DEPLOYPATH=/home/MADADYEMEN/public_html  # Add /<app_folder> if required

        - /bin cp * $DEPLOYPATH                           #copy all from root 
      